export const BASE_HP = 15
export const STARTING_COINS = 75
export const TOWER_COST = 25
export const TOWER_FIRE_RATE = 650
export const TOWER_DAMAGE = 10
export const ENEMY_BASE_HP = 30
export const ENEMY_HP_PER_WAVE = 6
export const ENEMY_BASE_SPEED = 1
export const ENEMY_SPEED_PER_WAVE = 0.1
export const ENEMY_BASE_REWARD = 6
export const ENEMY_REWARD_PER_WAVE = 2
export const ENEMIES_PER_WAVE = 6
export const ENEMIES_PER_WAVE_GROWTH = 2
export const WAVE_BREAK_MS = 3000
export const MIN_SPAWN_DELAY_MS = 400
export const MAP_HEIGHT_TILES = 15
export const MAP_WIDTH_TILES = 20
export const MAP_ROAD_LENGTH_TILES = (MAP_HEIGHT_TILES + MAP_WIDTH_TILES) * 2
